version: "2"
services:
    api:
        image: charapadev/cakenview-api
        ports:
            - 8080:8080
    db:
        image: postgres:latest
        ports:
            - 5432:5432
        environment:
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_DB=cakenview
