@host = http://localhost:8080
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ0ZXN0ZUBnbWFpbC5jb20ifQ._2prLpL28VbcOcOz0vKzXC9wBKuGQx-DOfkWICmenfU

###

# Lista todos os bolos

GET {{host}}/cakes
Authorization: {{token}}

###

# Lista os bolos em destaque

GET {{host}}/cakes/trendings

###

# Mostra o bolo do dia

GET {{host}}/cakes/daily

###

# Adiciona um novo bolo

POST {{host}}/cakes
Content-Type: application/json
Authorization: {{token}}

{
    "name": "Bolo de morango com creme",
    "description": "A primeira coisa que chama a atenção é a sua aparência irresistível. A base do bolo é um pão-de-ló macio e úmido, adornado com camadas generosas de creme de baunilha fresco e suave. O contraste de cores entre o vermelho intenso dos morangos maduros e o branco cremoso do recheio é um espetáculo para os olhos.",
    "imageUrl": "https://spicysouthernkitchen.com/wp-content/uploads/strawberry-twinkie-cake-6.jpg"
}
###

# Buscar um bolo pelo identificador

GET {{host}}/cakes/1
Authorization: {{token}}

###

# Remove um bolo

DELETE {{host}}/cakes/1

###

# Lista avaliações sobre um bolo

GET {{host}}/ratings?cakeId=1

###

# Avalia um bolo

POST {{host}}/ratings
Content-Type: application/json
Authorization: {{token}}

{
    "cakeId": 1,
    "number": 5,
    "comment": "Eri bolo bom"
}

###

# Cadastra um usuário

POST {{host}}/users
Content-Type: application/json

{
    "email": "teste@gmail.com",
    "password": "teste123"
}

###

# Requisita token de autenticação

POST {{host}}/login
username: teste@gmail.com
password: teste123
