# Listar bolos

GET http://localhost:8080/cakes
###
# Listar os bolos em destaque 

GET http://localhost:8080/cakes/trending
###
# Buscar o bolo escolhido do dia 

GET http://localhost:8080/cakes/daily
###
# Adicionar um novo bolo

POST http://localhost:8080/cakes
Content-Type: application/json

{
    "name": "Bolo de morango com creme",
    "description": "A primeira coisa que chama a atenção é a sua aparência irresistível. A base do bolo é um pão-de-ló macio e úmido, adornado com camadas generosas de creme de baunilha fresco e suave. O contraste de cores entre o vermelho intenso dos morangos maduros e o branco cremoso do recheio é um espetáculo para os olhos.",
    "imageUrl": "https://spicysouthernkitchen.com/wp-content/uploads/strawberry-twinkie-cake-6.jpg"
}
###
# Buscar um bolo pelo identificador

GET http://localhost:8080/cakes/1
###
# Remover um bolo

DELETE http://localhost:8080/cakes/1