jwt:
    secret: vdDq4hVKoodLKB6UtXnT6VuIvep3UyuxJS7qRj7jWCOpa2CunG7WyavMlg35zo8L
spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/cakenview
        username: postgres
        password: postgres
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
